ADMIN_ROLE = "Admin"
LIBRARIAN_ROLE = "Librarian"
USER_ROLE = "User"
AESCRYPT_SECRET_PASSWORD ="(@ps@123"

#Mails Info
WELCOME_MAIL_SUBJECT = "Welcome to LMS"
FORGOT_PASSWORD_MAIL_SUBJECT = "LMS - Forgot Password"